### ISSUE TITLE
Alpha

### ISSUE THREAD

**Issue by lastmjs** [lastmjs/ethereum-pm#1]
- [x] We'll have to wait for MetaMask v8.0.0 for any of this to be truly usable
- [x] Generate or allow user to manually input Ethereum private key or mnemonic phrase
- [x] Encrypt message
  - [x] Figure out the best way to do encryption, should we use the private key directly, or generate some kind of encryption key?
- [x] Post the message to swarm
- [x] Create a link to the message on ethereumpm.com, create a transaction, encode it using utf-8 or something, then send a transaction with 0 ETH value and the data to the address that the user desires to send the message to
- [x] When a user receives the transaction and looks at the data field, they will copy the link and paste it into their browser. Ethereum PM will grab the swarm hash and retrieve the encrypted file contents. Then, they will have to put their private key into the app and have the file decrypted.
- [x] The homepage should show all messages for the current account if possible...hopefully we can search through transactions based on the data field, we'll see...perhaps for this type of search functionality, we'll need a smart contract to keep track of all of this
- [x] The above is just for the alpha, which I don't expect anyone would actually want to use on the Ethereum main network because they would have to expose their private key to the app. We really need MetaMask to include this type of functionality natively
- [x] Waiting on MetaMask encrypt/decrypt functionality to really make an MVP: https://github.com/MetaMask/metamask-extension/issues/1190
- [x] I might need to get public key's from the addresses that the user puts in, if MetaMask does not do it for me:
  - [x] https://github.com/ethers-io/ethers.js/issues/700 This should help me recover the public key from an Ethereum transaction
  - [x] So, before a message can be encrypted for an address, the account that the address corresponds to must have submitted at least one transaction to Ethereum. I'll have to use ethersjs getHistory from the Etherscan provider to get at least one transaction...it would be nice to not have to rely on Etherscan for this
- [x] Figure out deriving public key from address, I am close: https://github.com/ethers-io/ethers.js/issues/700
- [x] Get rid of 0x in data field if possible
- [x] Make what we have look beautiful
- [x] Handle all error cases elegantly. Make everything very robust
